[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Solutions for Advent of Code 2025!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
    "termcolor>=3.2.0",
]
